### ISSUE TITLE
Provide simple example to get started

### ISSUE THREAD

**Issue by JoostvanPinxten** [OneMoreGres/qtc-gtest#1]
I'm new to Google's C++ testing framework, although I have got experience with JUnit and PyUnit. 

I'm a fan of Qt Creator so I was pleasantly surprised that a plugin exists for this.

However, it would be a very nice kick-start if there would just be a simple example/tutorial to get started. It would greatly ease the adoption for me! I could not find any documentation on how to set up the Google Test library with your plugin and how it understands where it should start.

Any plans to add such documentation/tutorial/examples?

**Comment by JoostvanPinxten** [comment]
You are right to assume that module tests should not be allowed to take any data from the console input. So your method does work, I was maybe just stating the obvious (attaching no judgement).

On another note, I've just tried again, and everything looks setup properly now.

**Comment by OneMoreGres** [comment]
Glad to hear it. Let me know when you will have more questions.
