### ISSUE TITLE
Default shortcut bindings overlap with Tools menu

### ISSUE THREAD

**Issue by JoostvanPinxten** [OneMoreGres/qtc-gtest#11]
The `Alt + T` in both the Windows and Ubuntu Qt Creator is bound to the Tools menu; therefore, I cannot access the Google Test submenu through these key bindings.

**Comment by OneMoreGres** [comment]
It works great for russian translation that i use :) Anyway you can change hotkeys in `Environment->Keyboard` options tab.

**Comment by JoostvanPinxten** [comment]
Well, apparently this is a wontfix then? :-)

I'd prefer some cleaner defaults, or perhaps I should consider switching to the Russian translation ;-)

**Comment by OneMoreGres** [comment]
Suggest a good hotkeys and i'll make it (maybe even locale-dependant).
For now, yeah, learn Russian... ;)

**Comment by JoostvanPinxten** [comment]
Well, just had a look at the keybindings, and e.g. Alt+D, Alt+X is not used yet. Too bad that the menu's have priority over the other keybindings.

BTW: I'm used to Eclipse, where Alt+Shift+X, T starts testing in execution mode, and Alt+Shift+D, T starts it in debug mode. So anything that resembles that is also fine by me. 

P.S. Before I learn Russian, I will learn Macedonian ;-) Јивели!

**Comment by OneMoreGres** [comment]
T means testing, so it's more intuitive than D (Debug?) or X (eXecute?). So does "Ctrl+Alt+T, A" sounds better for you?

**Comment by JoostvanPinxten** [comment]
Sounds perfect, that one wasn't taken either. And no, it doesn't, but Eclipse has gotten me used to those keybindings. ;-)
