### ISSUE TITLE
Qt Creator hangs when detecting this failed test...

### ISSUE THREAD

**Issue by JoostvanPinxten** [OneMoreGres/qtc-gtest#12]
I've got one particular situation in which the QtCreator in Linux only... This is with the latest Qt 3.4.0 Gtest build that you provided in issue #10.

The strange thing is, however, is that I can only reproduce this in a very particular failure (see below). To make it stranger, the bug won't trigger when I only have the tsplib-parser project loaded. It needs to be inside the other project (which I can't share yet right now), for the problem to manifest. Could it have to do with the fact that I have two separate instances of gtest in that project. There is one gtest executable for the project itself, the other one is inherited from tsplib-parser (which is in the parser subdir).

```
Starting /home/jvpinxten/build-cph-tsp-Desktop_Qt_5_3_GCC_64bit-Debug/parser/tests/tests...
Running main() from gtest_main.cc
[==========] Running 18 tests from 5 test cases.
[----------] Global test environment set-up.
[----------] 5 tests from Basic_ParserTest
[ RUN      ] Basic_ParserTest.Name
[       OK ] Basic_ParserTest.Name (0 ms)
[ RUN      ] Basic_ParserTest.NameKeywordInField
[       OK ] Basic_ParserTest.NameKeywordInField (0 ms)
[ RUN      ] Basic_ParserTest.CommentKeywordInField
[       OK ] Basic_ParserTest.CommentKeywordInField (0 ms)
[ RUN      ] Basic_ParserTest.FloatingPointExponent
[       OK ] Basic_ParserTest.FloatingPointExponent (0 ms)
[ RUN      ] Basic_ParserTest.DataAfterSection
[       OK ] Basic_ParserTest.DataAfterSection (0 ms)
[----------] 5 tests from Basic_ParserTest (0 ms total)

[----------] 2 tests from Parser_TourTest
[ RUN      ] Parser_TourTest.Basic
[       OK ] Parser_TourTest.Basic (0 ms)
[ RUN      ] Parser_TourTest.IncorrectType
[       OK ] Parser_TourTest.IncorrectType (1 ms)
[----------] 2 tests from Parser_TourTest (1 ms total)

[----------] 6 tests from Parser_TSPTest
[ RUN      ] Parser_TSPTest.IntegerArray1
[       OK ] Parser_TSPTest.IntegerArray1 (0 ms)
[ RUN      ] Parser_TSPTest.IntegerArray2
[       OK ] Parser_TSPTest.IntegerArray2 (0 ms)
[ RUN      ] Parser_TSPTest.IntegerArray3
[       OK ] Parser_TSPTest.IntegerArray3 (0 ms)
[ RUN      ] Parser_TSPTest.RealArray1
[       OK ] Parser_TSPTest.RealArray1 (0 ms)
[ RUN      ] Parser_TSPTest.MixedArray1
[       OK ] Parser_TSPTest.MixedArray1 (0 ms)
[ RUN      ] Parser_TSPTest.IncorrectType
[       OK ] Parser_TSPTest.IncorrectType (0 ms)
[----------] 6 tests from Parser_TSPTest (0 ms total)

[----------] 3 tests from Parser_TSPEdgeTest
[ RUN      ] Parser_TSPEdgeTest.EUC_2D
[       OK ] Parser_TSPEdgeTest.EUC_2D (0 ms)
[ RUN      ] Parser_TSPEdgeTest.EXPLICIT_FULL_MATRIX_WRONG_DIMENSION
[       OK ] Parser_TSPEdgeTest.EXPLICIT_FULL_MATRIX_WRONG_DIMENSION (0 ms)
[ RUN      ] Parser_TSPEdgeTest.EXPLICIT_FULL_MATRIX
[       OK ] Parser_TSPEdgeTest.EXPLICIT_FULL_MATRIX (0 ms)
[----------] 3 tests from Parser_TSPEdgeTest (0 ms total)

[----------] 2 tests from GTSP
[ RUN      ] GTSP.Basic_instance
[       OK ] GTSP.Basic_instance (0 ms)
[ RUN      ] GTSP.AGTSP_4br17
../../../cph-tsp/parser/tests/gtsptests.cpp:82: Failure
Value of: clusters.size()
  Actual: 17
Expected: 4u
Which is: 4
../../../cph-tsp/parser/tests/gtsptests.cpp:83: Failure
Value of: clusters[0].size()
  Actual: 1
Expected: 2u
Which is: 2
[  FAILED  ] GTSP.AGTSP_4br17 (1 ms)
[----------] 2 tests from GTSP (1 ms total)

[----------] Global test environment tear-down
[==========] 18 tests from 5 test cases ran. (2 ms total)
[  PASSED  ] 17 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] GTSP.AGTSP_4br17

 1 FAILED TEST
/home/jvpinxten/build-cph-tsp-Desktop_Qt_5_3_GCC_64bit-Debug/parser/tests/tests exited with code 1```

**Comment by OneMoreGres** [comment]
And what is the plugin's bug? It doesn't parse output, crashes qtc, fails to start tests, generates wrong filters? You didn't mention.

**Comment by JoostvanPinxten** [comment]
It crashes Qt. However, only when I start it from the 'other' project, in Ubuntu only. Top shows me that Qt Creator is using (almost) 100% CPU and Qt Creator becomes unresponsive (also does not show the output). I need to kill the process. If I disable the plugin, the whole test output gets displayed as expected, but I cannot deduce what the real problem is here.

I understand that it's difficult to assess what the reason could be. But I think you have a decent idea about my project setup. I might be able to share the project in some time.

**Comment by OneMoreGres** [comment]
Possible it triggers some assertion. I'll look at parsing code to see if i missed something based on your sample. But yes, it's hard to fix unreproducible problem.

**Comment by JoostvanPinxten** [comment]
Are those assertions reported anywhere? I can have another look. 

When I get more time, I can try to make a reproducable example.

**Comment by OneMoreGres** [comment]
Release build got QT_NO_DEBUG flag that disables assertions, so there is no prints, just crash/undefined behaviour.

There is version with enabled assertions (and proper keybindings).
http://rghost.ru/private/8TQfgQflB/a43c1b76506523df7431227681ae7326

  md5: 94015353a73b30cda00cea08e08f95e9  libQtcGtest.so

**Comment by OneMoreGres** [comment]
Haven't found something really suspicious.

Just in case, there is version with assertions for 3.5.0:
http://rghost.ru/private/7Q7447MxX/22d4f65d5b30d064284590d9c00f73f5
  md5: 3af880bc069d5c19aa53ccbdc24fc988  libQtcGtest.so

**Comment by JoostvanPinxten** [comment]
Interesting. I run qtcreator from commandline, but it outputs nothing. The process does pick up the output data from gtest, and sometimes shows it, but it never completes.

Without your plugin enabled, everything works as I expected. So it's not triggering any assertions anywhere. Using the 3.4.0 build on the 3.4.2 Qt Creator.

Updated to 3.5.0; same behaviour. No output is generated.

**Comment by JoostvanPinxten** [comment]
Here's a [minimal example](http://rghost.net/7XXY9r2rk) that reproduces the problem. It consistently hangs for me. In both Release and Debug modes.

I'm using `g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4`. Please le me know if you need more information!

**Comment by OneMoreGres** [comment]
Thanks, i've found the error! It was really stupid.

Try it:
http://rghost.ru/private/6wl6CSvk5/f742feb82cddbbe7c283f870272f117a
http://rghost.ru/private/7rrLxFRB5/21c3736ebc56c817c4301e60c2a1772b

  md5sum QtcGtest-3.5.0_1-linux-x64.tar.gz 
  9bb47da0f170fc60155e169c9721051f  QtcGtest-3.5.0_1-linux-x64.tar.gz

  md5sum QtcGtest-3.5.0_1-win.zip 
  29912b4ee2c226d911f13b40c604179b  QtcGtest-3.5.0_1-win.zip

**Comment by JoostvanPinxten** [comment]
Not sure what the error was, and how I triggered it now, but I'm glad the minimal example helped.

Your latest build fixes it :-) Thanks!

**Comment by OneMoreGres** [comment]
Trigger: test fail in file that could not be found from gtest's print (`../../fileName`).
So making some tests fail in such nested project should freeze old plugin version.
