### ISSUE TITLE
Marks does not clear between runs.

### ISSUE THREAD

**Issue by CJCombrink** [OneMoreGres/qtc-gtest#14]
The marks does not get cleared correctly between test runs if an error gets resolved. 
Also when an error occurs again, a new mark is added on top of the old mark.

Looking at the code through GitHub it seems like nobody is calling "OutputPane::clearContents()", but I might overlook something.

I am using Qt Creator 4.0.3 on Ubuntu 16.04.

Related but not sure if by design: When clicking the mark your output pane is not set to focus. It does select the correct issue in your pane but if another pane is shown (for example Application Output) then you need to manually open the Google Test pane.

_PS: Awesome plugin_

**Comment by OneMoreGres** [comment]
Hello!
Found it by myself some time ago, but was too lazy to fix. But as soon as someone else pointed at it, there is no more excuses for me :) Just a question of free time.
Suggestion seems reasonable too. Should try it too.

P.S. Sorry for long response.

**Comment by OneMoreGres** [comment]
Looks like fixed. You can try this test binary (not exactly your version, but it should be binary compatible).
[QtcGtest-4.0.2-linux-x64.tar.gz](https://github.com/OneMoreGres/qtc-gtest/files/409419/QtcGtest-4.0.2-linux-x64.tar.gz)
