### ISSUE TITLE
Unable to open file if test fails.

### ISSUE THREAD

**Issue by CJCombrink** [OneMoreGres/qtc-gtest#17]
When using the latest plugin with Qt Creator 4.2 I get the following issue when clicking a failed test in the output pane:

> File Error: 
> Could not open "..\TestGtest\main.cpp" for reading. Either the file does not exist or you do not have the permissions to open it.

Is this a bug or is there something that I have not configured?

System:
Windows 7
Qt Creator: 4.2.1
QtcGtest Plugin: 4.2.0_1

**Comment by OneMoreGres** [comment]
Hi! Should work now.
Seems nobody use it because it never worked on windows :D

**Comment by JoostvanPinxten** [comment]
I've actually noticed this bug before, but I expected it to be due to the weird project structure I typically used. It is convenient when you have bigger projects, but that hasn't become a hindrance to me yet :-)

**Comment by OneMoreGres** [comment]
If file in error message is relative then plugin tries to find same path in project files.
So if error in some other project or somewhere else then it will successfully fail :)

Btw there is compiled windows binary to test if i missed something again.
[QtcGtest-4.2.1-win.zip](https://github.com/OneMoreGres/qtc-gtest/files/1011933/QtcGtest-4.2.1-win.zip)

**Comment by CJCombrink** [comment]
@OneMoreGres The updated plugin works, thank you very much.

> Seems nobody use it because it never worked on windows :D

I always used the plugin in Linux, but recently changed jobs and now need to work in Windows :(

I still prefer your plugin above the bundled "AutoTest" plugin.
