### ISSUE TITLE
No results shown

### ISSUE THREAD

**Issue by amitiunin** [OneMoreGres/qtc-gtest#19]
Results of a test are only shown in "Application Output" and not in "Google Test".
Output begins with that:
`&"warning: GDB: Failed to set controlling terminal: \320\235\320\265\320\277\321\200\320\270\320\274\320\265\320\275\320\270\320\274\321\213\320\271 \320\272 \320\264\320\260\320\275\320\275\320\276\320\274\321\203 \321\203\321\201\321\202\321\200\320\276\320\271\321\201\321\202\320\262\321\203 ioctl\n"`
After this tests run but the Google Test panel shows nothing. (In fact, Qt Autotest plugin doesn't show anything, too.)
Using Ubuntu 16.04, Qt Creator v4.4.0, version of plugin the same. Project is CMake-based, can give a link to repo if necessary.

**Comment by OneMoreGres** [comment]
Qtc's internal API changed: it is no more possible to capture process output. So pluging doesn't parse test results (at least for now).

**Comment by amitiunin** [comment]
Understood. Hope it will change :)

**Comment by OneMoreGres** [comment]
I've restored ability to parse output, but only when test run was initiated by plugin (just like Qt Autotest plugin does). Prebuilt versions should be in releases soon.
