### ISSUE TITLE
Tools -> Google Test crashes on Linux

### ISSUE THREAD

**Issue by vittali** [OneMoreGres/qtc-gtest#20]
On Mint 18, calling a menu entry crashes qtcreator, the same is true for clicking on check current ,etc in the Google Test pane. The Google Test panes remains empty when CTRL+R running tests.

**Comment by OneMoreGres** [comment]
I'll check crashes, but ctrl+r will not work anymore (qtc api change).

**Comment by OneMoreGres** [comment]
Also updated linux binaries in releases section.

**Comment by vittali** [comment]
Excellent, thanks for the fast bug fix.
Peter
