### ISSUE TITLE
Does not show TEST_P results

### ISSUE THREAD

**Issue by daiw** [OneMoreGres/qtc-gtest#3]
Hi,
thanks for this plug-in, I like it very much.

My issue is: it does not show results of Value Parameterized Tests ( https://code.google.com/p/googletest/wiki/AdvancedGuide#Value_Parameterized_Tests ).
It would be cool, if this could be added.

**Comment by OneMoreGres** [comment]
Hi. Ok, i'll make it.

**Comment by OneMoreGres** [comment]
Done. You can download it from [sourceforge](https://sourceforge.net/projects/qtc-gtest/files/bin/) now.

**Comment by daiw** [comment]
thx, it's working :+1:

**Comment by OneMoreGres** [comment]
Glad to help :)
