### ISSUE TITLE
Show disabled test and filters

### ISSUE THREAD

**Issue by oiaavb** [OneMoreGres/qtc-gtest#4]
Thank you for this really great plugin.

One thing that would be great is if the plugin would mention test marked with DISABLED_ like the output prints in yellow:
![01](https://cloud.githubusercontent.com/assets/8997015/5933241/be70f0b8-a6bd-11e4-8344-a9f87452a84b.PNG)
and activated filter like --gtest_filter=StackTest.* which the output also prints in yellow:
![02](https://cloud.githubusercontent.com/assets/8997015/5933251/ed4e2d4c-a6bd-11e4-8d8a-d7869a57342a.PNG)

Otherwise you can quickly forget that you disalbed some tests or added a filter and you are actually not running all your test without being aware of it :)

**Comment by OneMoreGres** [comment]
Thanks. Got a lot of work right now, but i'll make it asap.
Btw, plugin can run and filter tests by its own. With some issues however, but it can :) (a little more info in [readme.md](https://github.com/OneMoreGres/qtc-gtest/blob/master/README.md))

**Comment by OneMoreGres** [comment]
Done. You can download it from [sourceforge](https://sourceforge.net/projects/qtc-gtest/files/bin/) now.

**Comment by oiaavb** [comment]
The output of --gtest_filter works great. But test marked with DISABLED_ will not be mentioned in the test output. Seems there is a problem or I am doing something wrong?

**Comment by OneMoreGres** [comment]
No problem :)
