### ISSUE TITLE
Failing TEST_P tests are not counted

### ISSUE THREAD

**Issue by oiaavb** [OneMoreGres/qtc-gtest#5]
If I run this test:
```c++
// Function under test...
bool acceptAtoC(char name) {
  if(name == 'b')
	return false;
  return true;
}

class MyStringTest : public testing::TestWithParam<char> {};

INSTANTIATE_TEST_CASE_P(InstantiationName,
						MyStringTest,
						::testing::Values('a', 'b', 'c'));

TEST_P(MyStringTest, testCase) {
  ASSERT_TRUE(acceptAtoC(GetParam()));
}
```
case b should fail and marked as red. But it isn't and the sum of failing tests is 0 instead of 1.

![04](https://cloud.githubusercontent.com/assets/8997015/6439203/bb55c82c-c0d0-11e4-8b15-8aa82efc1a94.PNG)

It this a bug, or am I doing something wrong here?

**Comment by OneMoreGres** [comment]
Hi.
Yes, it's a bug. I'll fix it asap.

**Comment by OneMoreGres** [comment]
Fixed, building binaries.

**Comment by OneMoreGres** [comment]
Finally done. Now you can download and test it.

**Comment by oiaavb** [comment]
Great, thank you.
