### ISSUE TITLE
Integrate in QtCreator sources

### ISSUE THREAD

**Issue by francoisferrand** [OneMoreGres/qtc-gtest#9]
Hello!
Thank you for this great plugin! To simplify maintenance and help advance the QtCreator platform as a whole, would you be willing to submit this plugin for integration into the QtCreator source tree?
Thanks!

**Comment by OneMoreGres** [comment]
Hello!
I don't plan to do this. At least for now. Because i don't work on plugins and integration into QTC distribution means some work to be done now and regular in future.

**Comment by Typz** [comment]
That's too bad... As I understand it, you actually get the integration for free (at least the frequent, easy bits) if it's in the main distribution...

**Comment by OneMoreGres** [comment]
Yes, it's free. But i meant that i must prepare code, pass review, maintain and develop it later if i want my plugins to be included into main distribution.
It's not so hard, but it must be done.

**Comment by Typz** [comment]
Sure, that's always the same problem... Would have been nice to help get the qtest plugin (and/or a generic unit test framework/plugin) in the 'base' qt creator...

Anyway, thanks again for you plugins.
Best regards,

**Comment by OneMoreGres** [comment]
Afaik [there is](http://doc.qt.io/qtcreator/creator-autotest.html) experimental Qt Test plugin in Qt Creator. But it ships with professional or enterprise editions.

**Comment by Typz** [comment]
That's indeed what I am referring to: i believe unit test support should be a platform feature, even if advanced qtest or squish integration is reserved for pro/enterprise.

**Comment by OneMoreGres** [comment]
Yes, i agree. It looks like a core feature. I was a bit disappointed when i heard that Digia made that plugin commercial only.

**Comment by JoostvanPinxten** [comment]
How does this plugin now relate to http://doc.qt.io/qtcreator/creator-autotest.html? It seems that this functionality has quite a tight integration into Qt Creator 4. It is also available for the free version, although it is still labelled as experimental at the moment though.

**Comment by OneMoreGres** [comment]
Default plugin can do almost everything same as mine and some more. It also likely has better support. So i don't have plans for further improvements of my plugin, but i'll compile it for new qtc versions until api will change too much.

**Comment by OneMoreGres** [comment]
Looks like it is finally done. Default plugin now has all features (at least stable ones).
I'm closing this issue and mark plugin as deprecated.
